### ISSUE TITLE
WKInterfaceMap does not Load Map

### ISSUE THREAD

**Issue by toan12520447** [happywatch/HelloWatchKit#1]
i can't load Map with iso simulator

**Comment by benmorrow** [comment]
Yep, i can confirm I see this too. It seems to be a known issue ([1](http://stackoverflow.com/questions/36910019/map-tiles-dont-load-in-xcode-7-3-watch-simulator), [2](http://stackoverflow.com/questions/27711298/cant-get-map-preview-to-load-in-watchkit-6-2-beta-using-swift), [3](https://forums.developer.apple.com/thread/14632)). As a workaround, if you can load the app up on a physical device, you'll see the map display correctly.
